package org.pexserver.koukunn.bettersurvival.Modules.Feature.DiscordWebhook;

import javax.imageio.ImageIO;
import java.awt.BasicStroke;
import java.awt.Color;
import java.awt.Font;
import java.awt.FontFormatException;
import java.awt.GradientPaint;
import java.awt.Graphics2D;
import java.awt.RenderingHints;
import java.awt.geom.RoundRectangle2D;
import java.awt.image.BufferedImage;
import java.io.ByteArrayOutputStream;
import java.io.IOException;
import java.io.InputStream;
import java.time.Instant;
import java.time.ZoneId;
import java.time.format.DateTimeFormatter;
import java.util.List;

public final class StatusImageRenderer {
    private static final int WIDTH = 1200;
    private static final int HEIGHT = 675;
    private static final DateTimeFormatter TIME_FORMAT = DateTimeFormatter.ofPattern("yyyy/MM/dd HH:mm:ss")
            .withZone(ZoneId.systemDefault());
    private static volatile Font baseFont;

    private StatusImageRenderer() {
    }

    public static byte[] render(StatusImageData data) throws IOException {
        BufferedImage image = new BufferedImage(WIDTH, HEIGHT, BufferedImage.TYPE_INT_ARGB);
        Graphics2D g = image.createGraphics();
        g.setRenderingHint(RenderingHints.KEY_ANTIALIASING, RenderingHints.VALUE_ANTIALIAS_ON);
        g.setRenderingHint(RenderingHints.KEY_RENDERING, RenderingHints.VALUE_RENDER_QUALITY);
        g.setRenderingHint(RenderingHints.KEY_TEXT_ANTIALIASING, RenderingHints.VALUE_TEXT_ANTIALIAS_ON);

        g.setPaint(new GradientPaint(0, 0, new Color(10, 16, 28), WIDTH, HEIGHT, new Color(22, 41, 74)));
        g.fillRect(0, 0, WIDTH, HEIGHT);

        g.setColor(new Color(255, 255, 255, 18));
        g.fillOval(-120, -100, 420, 420);
        g.fillOval(860, 360, 360, 360);

        drawCard(g, 42, 38, WIDTH - 84, HEIGHT - 76, new Color(7, 12, 23, 220));

        g.setColor(Color.WHITE);
        g.setFont(font(Font.BOLD, 42));
        g.drawString(data.serverName(), 74, 104);

        g.setColor(new Color(173, 194, 255));
        g.setFont(font(Font.PLAIN, 22));
        g.drawString("Minecraft Server Status", 76, 138);

        drawBadge(g, 76, 164, 220, 76, new Color(63, 190, 120), "ONLINE", data.onlinePlayers() + " / " + data.maxPlayers());
        drawBadge(g, 316, 164, 250, 76, new Color(81, 139, 255), "UPDATED", TIME_FORMAT.format(data.updatedAt()));

        drawPanel(g, 74, 276, 330, 286, "Overview");
        drawMetric(g, 98, 334, "Players", data.onlinePlayers() + " / " + data.maxPlayers(), new Color(127, 236, 173));
        drawMetric(g, 98, 412, "Minecraft Time", data.minecraftTime(), new Color(120, 190, 255));
        drawMetric(g, 98, 490, "CPU / Heap", data.cpuText() + " / " + data.heapText(), new Color(255, 196, 111));
        drawMetric(g, 98, 568, "TPS", data.tpsText(), new Color(255, 131, 131));

        drawPanel(g, 430, 164, 696, 398, "Online Players");
        drawPlayers(g, 454, 214, 648, 320, data.onlinePlayerNames());

        g.setColor(new Color(193, 205, 230));
        g.setFont(font(Font.PLAIN, 18));
        g.drawString("Generated by BetterSurvival DiscordWebhook", 76, 620);

        g.dispose();

        ByteArrayOutputStream output = new ByteArrayOutputStream();
        ImageIO.write(image, "png", output);
        return output.toByteArray();
    }

    private static void drawCard(Graphics2D g, int x, int y, int width, int height, Color color) {
        g.setColor(color);
        g.fill(new RoundRectangle2D.Float(x, y, width, height, 36, 36));
        g.setColor(new Color(255, 255, 255, 24));
        g.setStroke(new BasicStroke(1.4f));
        g.draw(new RoundRectangle2D.Float(x, y, width, height, 36, 36));
    }

    private static void drawPanel(Graphics2D g, int x, int y, int width, int height, String title) {
        g.setColor(new Color(255, 255, 255, 14));
        g.fill(new RoundRectangle2D.Float(x, y, width, height, 28, 28));
        g.setColor(new Color(255, 255, 255, 22));
        g.setStroke(new BasicStroke(1.2f));
        g.draw(new RoundRectangle2D.Float(x, y, width, height, 28, 28));
        g.setColor(Color.WHITE);
        g.setFont(font(Font.BOLD, 28));
        g.drawString(title, x + 24, y + 42);
    }

    private static void drawBadge(Graphics2D g, int x, int y, int width, int height, Color accent, String label, String value) {
        g.setColor(new Color(accent.getRed(), accent.getGreen(), accent.getBlue(), 38));
        g.fill(new RoundRectangle2D.Float(x, y, width, height, 24, 24));
        g.setColor(accent);
        g.fillRoundRect(x + 18, y + 24, 12, 12, 12, 12);
        g.setColor(new Color(226, 233, 247));
        g.setFont(font(Font.BOLD, 16));
        g.drawString(label, x + 40, y + 29);
        g.setColor(Color.WHITE);
        g.setFont(font(Font.BOLD, 22));
        g.drawString(value, x + 18, y + 57);
    }

    private static void drawMetric(Graphics2D g, int x, int y, String label, String value, Color accent) {
        g.setColor(accent);
        g.setFont(font(Font.BOLD, 18));
        g.drawString(label, x, y);
        g.setColor(Color.WHITE);
        g.setFont(font(Font.BOLD, 28));
        g.drawString(value, x, y + 34);
    }

    private static void drawPlayers(Graphics2D g, int x, int y, int width, int height, List<String> names) {
        int columns = 3;
        int gap = 14;
        int itemHeight = 54;
        int itemWidth = (width - gap * (columns - 1)) / columns;

        if (names.isEmpty()) {
            g.setColor(new Color(200, 210, 232));
            g.setFont(font(Font.PLAIN, 26));
            g.drawString("No players online", x, y + 40);
            return;
        }

        for (int index = 0; index < names.size(); index++) {
            int row = index / columns;
            int col = index % columns;
            int px = x + col * (itemWidth + gap);
            int py = y + row * (itemHeight + gap);
            if (py + itemHeight > y + height) {
                break;
            }

            g.setColor(new Color(255, 255, 255, 18));
            g.fill(new RoundRectangle2D.Float(px, py, itemWidth, itemHeight, 18, 18));
            g.setColor(new Color(119, 210, 167));
            g.fillOval(px + 14, py + 18, 18, 18);
            g.setColor(Color.WHITE);
            g.setFont(font(Font.BOLD, 22));
            g.drawString(clip(names.get(index), 18), px + 44, py + 35);
        }
    }

    private static Font loadBaseFont() {
        Font cached = baseFont;
        if (cached != null) {
            return cached;
        }
        try (InputStream stream = StatusImageRenderer.class.getResourceAsStream("/fonts/NotoSansJP-VF.ttf")) {
            if (stream == null) {
                throw new IOException("/fonts/NotoSansJP-VF.ttf not found");
            }
            Font loaded = Font.createFont(Font.TRUETYPE_FONT, stream);
            baseFont = loaded;
            return loaded;
        } catch (IOException | FontFormatException e) {
            throw new IllegalStateException("Status image font load failed: " + e.getMessage(), e);
        }
    }

    private static Font font(int style, float size) {
        return loadBaseFont().deriveFont(style, size);
    }

    private static String clip(String value, int maxChars) {
        if (value == null) {
            return "";
        }
        if (value.length() <= maxChars) {
            return value;
        }
        return value.substring(0, Math.max(0, maxChars - 1)) + "…";
    }

    public record StatusImageData(
            String serverName,
            int onlinePlayers,
            int maxPlayers,
            List<String> onlinePlayerNames,
            String minecraftTime,
            String tpsText,
            String cpuText,
            String heapText,
            Instant updatedAt) {
    }
}
