package org.pexserver.koukunn.bettersurvival.Modules.Feature.DiscordWebhook;

import javax.imageio.ImageIO;
import java.awt.BasicStroke;
import java.awt.Color;
import java.awt.GradientPaint;
import java.awt.Graphics2D;
import java.awt.RenderingHints;
import java.awt.geom.RoundRectangle2D;
import java.awt.image.BufferedImage;
import java.io.ByteArrayOutputStream;
import java.io.IOException;
import java.time.Instant;
import java.time.ZoneId;
import java.time.format.DateTimeFormatter;
import java.util.HashMap;
import java.util.List;
import java.util.Locale;
import java.util.Map;

public final class StatusImageRenderer {
    private static final int WIDTH = 1200;
    private static final int HEIGHT = 675;
    private static final DateTimeFormatter TIME_FORMAT = DateTimeFormatter.ofPattern("MM/dd HH:mm")
            .withZone(ZoneId.systemDefault());
    private static final Map<Character, String[]> GLYPHS = createGlyphs();

    private StatusImageRenderer() {
    }

    public static byte[] render(StatusImageData data) throws IOException {
        BufferedImage image = new BufferedImage(WIDTH, HEIGHT, BufferedImage.TYPE_INT_ARGB);
        Graphics2D g = image.createGraphics();
        g.setRenderingHint(RenderingHints.KEY_ANTIALIASING, RenderingHints.VALUE_ANTIALIAS_ON);
        g.setRenderingHint(RenderingHints.KEY_RENDERING, RenderingHints.VALUE_RENDER_QUALITY);

        g.setPaint(new GradientPaint(0, 0, new Color(10, 16, 28), WIDTH, HEIGHT, new Color(22, 41, 74)));
        g.fillRect(0, 0, WIDTH, HEIGHT);

        g.setColor(new Color(255, 255, 255, 18));
        g.fillOval(-120, -100, 420, 420);
        g.fillOval(860, 360, 360, 360);

        drawCard(g, 42, 38, WIDTH - 84, HEIGHT - 76, new Color(7, 12, 23, 220));

        drawText(g, clip(sanitize(data.serverName()), 21), 74, 78, 6, 2, Color.WHITE);
        drawText(g, "MINECRAFT SERVER STATUS", 76, 126, 3, 1, new Color(173, 194, 255));

        drawBadge(g, 76, 164, 220, 76, new Color(63, 190, 120), "ONLINE",
                data.onlinePlayers() + " / " + data.maxPlayers());
        drawBadge(g, 316, 164, 332, 76, new Color(81, 139, 255), "UPDATED",
                TIME_FORMAT.format(data.updatedAt()));

        drawPanel(g, 74, 276, 330, 250, "OVERVIEW");
        drawMetric(g, 98, 334, "PLAYERS", data.onlinePlayers() + " / " + data.maxPlayers(), new Color(127, 236, 173));
        drawMetric(g, 98, 404, "WORLD TIME", clip(sanitize(data.minecraftTime()), 15), new Color(120, 190, 255));
        drawMetric(g, 98, 474, "TPS", clip(sanitize(data.tpsText()), 14), new Color(255, 131, 131));

        drawPanel(g, 430, 276, 696, 286, "SERVER");
        drawMetric(g, 454, 334, "CPU", clip(sanitize(data.cpuText()), 22), new Color(255, 196, 111));
        drawMetric(g, 454, 404, "HEAP", clip(sanitize(data.heapText()), 22), new Color(255, 196, 111));
        drawMetric(g, 454, 474, "PLAYERS ONLINE", String.valueOf(data.onlinePlayers()), new Color(127, 236, 173));

        drawPanel(g, 676, 164, 450, 86, "ONLINE PLAYERS");
        drawPlayers(g, 700, 202, 402, 34, data.onlinePlayerNames());

        drawText(g, "GENERATED BY BETTERSURVIVAL DISCORDWEBHOOK", 76, 614, 2, 1, new Color(193, 205, 230));

        g.dispose();

        ByteArrayOutputStream output = new ByteArrayOutputStream();
        ImageIO.write(image, "png", output);
        return output.toByteArray();
    }

    private static void drawCard(Graphics2D g, int x, int y, int width, int height, Color color) {
        g.setColor(color);
        g.fill(new RoundRectangle2D.Float(x, y, width, height, 36, 36));
        g.setColor(new Color(255, 255, 255, 24));
        g.setStroke(new BasicStroke(1.4f));
        g.draw(new RoundRectangle2D.Float(x, y, width, height, 36, 36));
    }

    private static void drawPanel(Graphics2D g, int x, int y, int width, int height, String title) {
        g.setColor(new Color(255, 255, 255, 14));
        g.fill(new RoundRectangle2D.Float(x, y, width, height, 28, 28));
        g.setColor(new Color(255, 255, 255, 22));
        g.setStroke(new BasicStroke(1.2f));
        g.draw(new RoundRectangle2D.Float(x, y, width, height, 28, 28));
        drawText(g, title, x + 24, y + 22, 3, 1, Color.WHITE);
    }

    private static void drawBadge(Graphics2D g, int x, int y, int width, int height, Color accent, String label, String value) {
        g.setColor(new Color(accent.getRed(), accent.getGreen(), accent.getBlue(), 38));
        g.fill(new RoundRectangle2D.Float(x, y, width, height, 24, 24));
        g.setColor(accent);
        g.fillRoundRect(x + 18, y + 24, 12, 12, 12, 12);
        drawText(g, label, x + 40, y + 18, 2, 1, new Color(226, 233, 247));
        drawText(g, sanitize(value), x + 18, y + 42, 3, 1, Color.WHITE);
    }

    private static void drawMetric(Graphics2D g, int x, int y, String label, String value, Color accent) {
        drawText(g, label, x, y, 2, 1, accent);
        drawText(g, sanitize(value), x, y + 22, 2, 1, Color.WHITE);
    }

    private static void drawPlayers(Graphics2D g, int x, int y, int width, int height, List<String> names) {
        int columns = 2;
        int gap = 14;
        int itemHeight = 54;
        int itemWidth = (width - gap * (columns - 1)) / columns;

        if (names.isEmpty()) {
            drawText(g, "NO PLAYERS ONLINE", x, y + 18, 3, 1, new Color(200, 210, 232));
            return;
        }

        for (int index = 0; index < names.size(); index++) {
            int row = index / columns;
            int col = index % columns;
            int px = x + col * (itemWidth + gap);
            int py = y + row * (itemHeight + gap);
            if (py + itemHeight > y + height) {
                break;
            }

            g.setColor(new Color(255, 255, 255, 18));
            g.fill(new RoundRectangle2D.Float(px, py, itemWidth, itemHeight, 18, 18));
            g.setColor(new Color(119, 210, 167));
            g.fillOval(px + 14, py + 18, 18, 18);
            drawText(g, sanitize(clip(names.get(index), 12)), px + 44, py + 16, 2, 1, Color.WHITE);
        }
    }

    private static void drawText(Graphics2D g, String text, int x, int y, int scale, int spacing, Color color) {
        if (text == null || text.isEmpty()) {
            return;
        }
        int cursorX = x;
        g.setColor(color);
        for (int i = 0; i < text.length(); i++) {
            char raw = text.charAt(i);
            if (raw == '\n') {
                cursorX = x;
                y += (7 * scale) + (4 * scale);
                continue;
            }
            char c = normalizeGlyph(raw);
            String[] glyph = GLYPHS.getOrDefault(c, GLYPHS.get('?'));
            for (int row = 0; row < glyph.length; row++) {
                String line = glyph[row];
                for (int col = 0; col < line.length(); col++) {
                    if (line.charAt(col) == '1') {
                        g.fillRect(cursorX + (col * scale), y + (row * scale), scale, scale);
                    }
                }
            }
            cursorX += (5 * scale) + spacing + scale;
        }
    }

    private static char normalizeGlyph(char c) {
        if (c <= 0x7F) {
            return Character.toUpperCase(c);
        }
        return '?';
    }

    private static String sanitize(String value) {
        if (value == null || value.isBlank()) {
            return "-";
        }
        StringBuilder builder = new StringBuilder(value.length());
        for (int i = 0; i < value.length(); i++) {
            char c = value.charAt(i);
            if (c == '\n') {
                builder.append('\n');
            } else if (c >= 32 && c <= 126) {
                builder.append(c);
            } else {
                builder.append('?');
            }
        }
        return builder.toString().toUpperCase(Locale.ROOT);
    }

    private static String clip(String value, int maxChars) {
        if (value == null) {
            return "";
        }
        if (value.length() <= maxChars) {
            return value;
        }
        return value.substring(0, Math.max(0, maxChars - 1)) + ".";
    }

    private static Map<Character, String[]> createGlyphs() {
        Map<Character, String[]> glyphs = new HashMap<>();
        glyphs.put('A', glyph("01110", "10001", "10001", "11111", "10001", "10001", "10001"));
        glyphs.put('B', glyph("11110", "10001", "11110", "10001", "10001", "10001", "11110"));
        glyphs.put('C', glyph("01111", "10000", "10000", "10000", "10000", "10000", "01111"));
        glyphs.put('D', glyph("11110", "10001", "10001", "10001", "10001", "10001", "11110"));
        glyphs.put('E', glyph("11111", "10000", "11110", "10000", "10000", "10000", "11111"));
        glyphs.put('F', glyph("11111", "10000", "11110", "10000", "10000", "10000", "10000"));
        glyphs.put('G', glyph("01111", "10000", "10000", "10011", "10001", "10001", "01110"));
        glyphs.put('H', glyph("10001", "10001", "10001", "11111", "10001", "10001", "10001"));
        glyphs.put('I', glyph("11111", "00100", "00100", "00100", "00100", "00100", "11111"));
        glyphs.put('J', glyph("11111", "00010", "00010", "00010", "00010", "10010", "01100"));
        glyphs.put('K', glyph("10001", "10010", "11100", "10010", "10001", "10001", "10001"));
        glyphs.put('L', glyph("10000", "10000", "10000", "10000", "10000", "10000", "11111"));
        glyphs.put('M', glyph("10001", "11011", "10101", "10101", "10001", "10001", "10001"));
        glyphs.put('N', glyph("10001", "10001", "11001", "10101", "10011", "10001", "10001"));
        glyphs.put('O', glyph("01110", "10001", "10001", "10001", "10001", "10001", "01110"));
        glyphs.put('P', glyph("11110", "10001", "10001", "11110", "10000", "10000", "10000"));
        glyphs.put('Q', glyph("01110", "10001", "10001", "10001", "10101", "10010", "01101"));
        glyphs.put('R', glyph("11110", "10001", "10001", "11110", "10100", "10010", "10001"));
        glyphs.put('S', glyph("01111", "10000", "10000", "01110", "00001", "00001", "11110"));
        glyphs.put('T', glyph("11111", "00100", "00100", "00100", "00100", "00100", "00100"));
        glyphs.put('U', glyph("10001", "10001", "10001", "10001", "10001", "10001", "01110"));
        glyphs.put('V', glyph("10001", "10001", "10001", "10001", "10001", "01010", "00100"));
        glyphs.put('W', glyph("10001", "10001", "10001", "10101", "10101", "10101", "01010"));
        glyphs.put('X', glyph("10001", "10001", "01010", "00100", "01010", "10001", "10001"));
        glyphs.put('Y', glyph("10001", "10001", "01010", "00100", "00100", "00100", "00100"));
        glyphs.put('Z', glyph("11111", "00001", "00010", "00100", "01000", "10000", "11111"));
        glyphs.put('0', glyph("01110", "10001", "10011", "10101", "11001", "10001", "01110"));
        glyphs.put('1', glyph("00100", "01100", "00100", "00100", "00100", "00100", "01110"));
        glyphs.put('2', glyph("01110", "10001", "00001", "00010", "00100", "01000", "11111"));
        glyphs.put('3', glyph("11110", "00001", "00001", "01110", "00001", "00001", "11110"));
        glyphs.put('4', glyph("00010", "00110", "01010", "10010", "11111", "00010", "00010"));
        glyphs.put('5', glyph("11111", "10000", "10000", "11110", "00001", "00001", "11110"));
        glyphs.put('6', glyph("01110", "10000", "10000", "11110", "10001", "10001", "01110"));
        glyphs.put('7', glyph("11111", "00001", "00010", "00100", "01000", "01000", "01000"));
        glyphs.put('8', glyph("01110", "10001", "10001", "01110", "10001", "10001", "01110"));
        glyphs.put('9', glyph("01110", "10001", "10001", "01111", "00001", "00001", "01110"));
        glyphs.put(' ', glyph("00000", "00000", "00000", "00000", "00000", "00000", "00000"));
        glyphs.put(':', glyph("00000", "00100", "00100", "00000", "00100", "00100", "00000"));
        glyphs.put('/', glyph("00001", "00010", "00100", "01000", "10000", "00000", "00000"));
        glyphs.put('-', glyph("00000", "00000", "00000", "11111", "00000", "00000", "00000"));
        glyphs.put('.', glyph("00000", "00000", "00000", "00000", "00000", "01100", "01100"));
        glyphs.put('%', glyph("11001", "11010", "00100", "01000", "10110", "00110", "00000"));
        glyphs.put('+', glyph("00000", "00100", "00100", "11111", "00100", "00100", "00000"));
        glyphs.put('(', glyph("00010", "00100", "01000", "01000", "01000", "00100", "00010"));
        glyphs.put(')', glyph("01000", "00100", "00010", "00010", "00010", "00100", "01000"));
        glyphs.put('?', glyph("01110", "10001", "00001", "00010", "00100", "00000", "00100"));
        glyphs.put('_', glyph("00000", "00000", "00000", "00000", "00000", "00000", "11111"));
        glyphs.put(',', glyph("00000", "00000", "00000", "00000", "00110", "00110", "00100"));
        return glyphs;
    }

    private static String[] glyph(String... rows) {
        return rows;
    }

    public record StatusImageData(
            String serverName,
            int onlinePlayers,
            int maxPlayers,
            List<String> onlinePlayerNames,
            String minecraftTime,
            String tpsText,
            String cpuText,
            String heapText,
            Instant updatedAt) {
    }
}
