name: Bettersurvival
version: "${version}"
main: org.pexserver.koukunn.bettersurvival.Loader
bootstrapper: org.pexserver.koukunn.bettersurvival.BetterSurvivalBootstrap
api-version: '26.3'
authors: [ Koukunn ]
description: PEXServer Plugin
